spring:
  application:
    name: mcp-host
  ai:
    openai:
      api-key: 
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
    mcp:
      client:
        initialized: false
        sse:
          connections:
            demo-server:
              url: http://localhost:8080
              sse-endpoint: /sse

server:
  port: 8082

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.mcphost: DEBUG
    org.springframework.ai: DEBUG
    io.modelcontextprotocol: DEBUG
